### ISSUE TITLE
Customize Timeout

### ISSUE THREAD

**Issue by danishkhan** [heroku/rendezvous.rb#8]
Seems like for some folks if the connection to Heroku takes to long a timeout occurs. The issue might be fixed with a customizable timeout, but I'm not too sure if that is the best solution.

You can find more information about the issue [here](https://github.com/travis-ci/dpl/issues/306).

**Comment by geemus** [comment]
@danishkhan yo! How have you been? It's been ages.

I think you can pass in customizable timeouts via the initialize: https://github.com/heroku/rendezvous.rb/blob/master/lib/rendezvous.rb#L31

If they aren't working we should definitely revisit though. The connect timeout is using Timeout though, which can be iffy in terms of working as desired, so I suppose that might be problematic. Still, may be worth trying to change settings and see if that helps at all.

Additionally, would certainly welcome doc improvements to make the options clearer.
